
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PONTO_E_VIRGULA = 7;
  public static final int WHERE = 4;
  public static final int BY = 6;
  public static final int ATRIBUTO = 12;
  public static final int EOF = 0;
  public static final int VIRGULA = 8;
  public static final int VALOR_NUMERICO = 14;
  public static final int TABELA = 11;
  public static final int IGUAL = 9;
  public static final int error = 1;
  public static final int SELECT = 2;
  public static final int FROM = 3;
  public static final int TODOS = 10;
  public static final int ERRO = 13;
  public static final int ORDER = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "FROM",
  "WHERE",
  "ORDER",
  "BY",
  "PONTO_E_VIRGULA",
  "VIRGULA",
  "IGUAL",
  "TODOS",
  "TABELA",
  "ATRIBUTO",
  "ERRO",
  "VALOR_NUMERICO"
  };
}

